#
# Source code address
# https://hub.docker.com/u/cuongtransc/
#
# Syntax: https://docs.docker.com/compose/compose-file/
#

version: "2.4"

x-default: &default
    networks:
        - comp_default
    cpu_shares: 512
    mem_limit: 100M
    # memswap_limit: 0           # 0 MB SWAP
    # privileged: true
    # restart: always
    # stdin_open: true
    # tty: true
    logging:
        driver: "json-file"
        options:
            max-size: "100M"
            max-file: "3"

services:
    mariadb:
        << : *default
        image: mariadb:10.1
        environment:
            - MYSQL_ROOT_PASSWORD=lab@secret
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress@123
            - MYSQL_DATABASE=wordpress
        #ports:
            #- "3306:3306"
        volumes:
            - ./mariadb-data/:/var/lib/mysql/
        hostname: mariadb

    wordpress:
        << : *default
        image: wordpress:5.3
        depends_on:
            - mariadb
        environment:
            - WORDPRESS_DB_HOST=mariadb
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress@123
            - WORDPRESS_DB_NAME=wordpress
        ports:
            - "80:80"
        hostname: wordpress

networks:
    comp_default:
        external: true

# volumes:
#     db-data:
