#
# Source code address
# https://hub.docker.com/u/cuongtransc/
#
# Syntax: https://docs.docker.com/compose/compose-file/
#
# Redis: https://hub.docker.com/_/redis/
#

version: "2"

services:
    redis:
        #image: redis:4-alpine
        image: bitnami/redis:4.0
        environment:
            - REDIS_PASSWORD=lab@123
        ports:
            - "6379:6379"
        networks:
            #- back
            - comp_default
        volumes:
            - ./redis-data/:/data/
        hostname: redis
        domainname: devopsz.com
        cpu_shares: 512
        mem_limit: 512M
        #privileged: true
        #restart: always
        #stdin_open: true
        #tty: true

networks:
    #back:
    comp_default:
        external: true

