#
# Source code address
# https://github.com/sameersbn/docker-gitlab
#
# Syntax: https://docs.docker.com/compose/compose-file/
#

version: "2"

services:
    postgres:
        image: postgres:10.2
        environment:
            - POSTGRES_USER=gitlab
            - POSTGRES_PASSWORD=password
        volumes:
            #- ./postgres-initdb.d/:/docker-entrypoint-initdb.d/
            - ./postgres-data/:/var/lib/postgresql/data/
        networks:
            - comp_default
        hostname: postgres
        domainname: coclab.lan
        cpu_shares: 512
        mem_limit: 1G
        #privileged: true
        #restart: always
        #stdin_open: true
        #tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

    redis:
        image: redis:4.0-alpine
        volumes:
            - ./redis-data/:/data/
        networks:
            - comp_default
        hostname: redis
        domainname: coclab.lan
        cpu_shares: 512
        mem_limit: 512M
        #privileged: true
        #restart: always
        #stdin_open: true
        #tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

    gitlab:
        image: sameersbn/gitlab:10.0.3
        depends_on:
            - redis
            - postgres
        ports:
            - "10080:80"
            - "10022:22"
        environment:
            - DEBUG=false

            - DB_ADAPTER=postgresql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=gitlab
            - DB_PASS=password
            - DB_NAME=gitlab

            - REDIS_HOST=redis
            - REDIS_PORT=6379

            - TZ=UTC
            - GITLAB_TIMEZONE=UTC

            - GITLAB_HTTPS=false
            - SSL_SELF_SIGNED=false

            - GITLAB_HOST=localhost
            - GITLAB_PORT=10080
            - GITLAB_SSH_PORT=10022
            - GITLAB_RELATIVE_URL_ROOT=
            - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
            - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
            - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

            - GITLAB_ROOT_PASSWORD=EGG@S3cR3T
            - GITLAB_ROOT_EMAIL=admin@eggclub.org

            - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
            - GITLAB_NOTIFY_PUSHER=false

            - GITLAB_EMAIL=notifications@example.com
            - GITLAB_EMAIL_REPLY_TO=noreply@example.com
            - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

            - GITLAB_BACKUP_SCHEDULE=daily
            - GITLAB_BACKUP_TIME=01:00

            - SMTP_ENABLED=false
            - SMTP_DOMAIN=www.example.com
            - SMTP_HOST=smtp.gmail.com
            - SMTP_PORT=587
            - SMTP_USER=mailer@example.com
            - SMTP_PASS=password
            - SMTP_STARTTLS=true
            - SMTP_AUTHENTICATION=login

            - IMAP_ENABLED=false
            - IMAP_HOST=imap.gmail.com
            - IMAP_PORT=993
            - IMAP_USER=mailer@example.com
            - IMAP_PASS=password
            - IMAP_SSL=true
            - IMAP_STARTTLS=false

            - OAUTH_ENABLED=false
            - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
            - OAUTH_ALLOW_SSO=
            - OAUTH_BLOCK_AUTO_CREATED_USERS=true
            - OAUTH_AUTO_LINK_LDAP_USER=false
            - OAUTH_AUTO_LINK_SAML_USER=false
            - OAUTH_EXTERNAL_PROVIDERS=

            - OAUTH_CAS3_LABEL=cas3
            - OAUTH_CAS3_SERVER=
            - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
            - OAUTH_CAS3_LOGIN_URL=/cas/login
            - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
            - OAUTH_CAS3_LOGOUT_URL=/cas/logout

            - OAUTH_GOOGLE_API_KEY=
            - OAUTH_GOOGLE_APP_SECRET=
            - OAUTH_GOOGLE_RESTRICT_DOMAIN=

            - OAUTH_FACEBOOK_API_KEY=
            - OAUTH_FACEBOOK_APP_SECRET=

            - OAUTH_TWITTER_API_KEY=
            - OAUTH_TWITTER_APP_SECRET=

            - OAUTH_GITHUB_API_KEY=
            - OAUTH_GITHUB_APP_SECRET=
            - OAUTH_GITHUB_URL=
            - OAUTH_GITHUB_VERIFY_SSL=

            - OAUTH_GITLAB_API_KEY=
            - OAUTH_GITLAB_APP_SECRET=

            - OAUTH_BITBUCKET_API_KEY=
            - OAUTH_BITBUCKET_APP_SECRET=

            - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
            - OAUTH_SAML_IDP_CERT_FINGERPRINT=
            - OAUTH_SAML_IDP_SSO_TARGET_URL=
            - OAUTH_SAML_ISSUER=
            - OAUTH_SAML_LABEL="Our SAML Provider"
            - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
            - OAUTH_SAML_GROUPS_ATTRIBUTE=
            - OAUTH_SAML_EXTERNAL_GROUPS=
            - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
            - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
            - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
            - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

            - OAUTH_CROWD_SERVER_URL=
            - OAUTH_CROWD_APP_NAME=
            - OAUTH_CROWD_APP_PASSWORD=

            - OAUTH_AUTH0_CLIENT_ID=
            - OAUTH_AUTH0_CLIENT_SECRET=
            - OAUTH_AUTH0_DOMAIN=

            - OAUTH_AZURE_API_KEY=
            - OAUTH_AZURE_API_SECRET=
            - OAUTH_AZURE_TENANT_ID=

            - AWS_BACKUPS=false
            - AWS_BACKUP_REGION=us-east-1
            #- AWS_BACKUP_ENDPOINT=
            - AWS_BACKUP_ACCESS_KEY_ID=
            - AWS_BACKUP_SECRET_ACCESS_KEY=
            - AWS_BACKUP_BUCKET=
            # - AWS_BACKUP_MULTIPART_CHUNK_SIZE=
            # - AWS_BACKUP_ENCRYPTION=false
            # - AWS_BACKUP_STORAGE_CLASS=STANDARD
        volumes:
            - ./gitlab-data/:/home/git/data
        networks:
            - comp_default
        hostname: gitlab
        domainname: coclab.lan
        cpu_shares: 512
        mem_limit: 3G
        #privileged: true
        #restart: always
        #stdin_open: true
        #tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

networks:
    comp_default:
        external: true

# volumes:
#     db-data:

