#
# syntax: https://docs.docker.com/compose/yml/
#

version: "2"

services:
    elasticsearch:
        image: elasticsearch:5.6-alpine
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - back
        volumes:
            #- ./config:/usr/share/elasticsearch/config
            - ./elasticsearch-data:/usr/share/elasticsearch/data
        hostname: elasticsearch
        domainname: devopsz.com
        cpu_shares: 1024
        mem_limit: 4G
        #privileged: true
        #restart: always
        #stdin_open: true
        tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

networks:
    back:

